### PR TITLE
Fixes: #59 Apply pep8

### PR DESCRIPTION
**Pull request by realaltffour**
I am so sorry of the multiple PRs, I hope it was worth the effort.

### CODE REVIEW

**Comment by realaltffour** [comment]
Hey @yochannah thanks! I would like to work on this but I would need some help since I couldn't find the change that resulted in travis failing out.

**Comment by yochannah** [comment]
hmm, so looking through the travis failures - there are some errors that are red herrings and can be ignored. The only lines that really matter are right at the end: https://travis-ci.org/intermine/intermine-ws-python/jobs/602794695#L3693-L3851 - there are several errors that look roughly the same. I think the first one is caused by this line - https://github.com/intermine/intermine-ws-python/pull/62/files#diff-75c783fc9876dfd43eefb18d77a5526eR369 

does that help? Pop by chat if not, I'm around all week, roughly 9-5:30 UK time :)

**Comment by realaltffour** [comment]
@yochannah @pep8speaks Is that a bug??

**Comment by yochannah** [comment]
errrrr..... I'm going to say yes, the lines pep8 is referring to don't correlate with the reported errors! 🤦‍♂

**Comment by yochannah** [comment]
Hey @realaltffour - sorry for letting this issue go quiet! It looks like we still have a few small test failures from some of the changed lines. Are you free to look at this still? If not, no worries - just let us know :)

**Comment by yochannah** [comment]
I am going to close this for now but if you want to come back or look at other issues later you are entirely welcome 🚀

**Pull request closed without merging**
