### PR TITLE
Committing organism specification on list upload functionality

### PR DESCRIPTION
**Pull request by nkengawoh**
@julie-sullivan 

Fixes: https://github.com/intermine/intermine-ws-python-docs/issues/33

Here is my update on this issue. Please could you review and give me feedback?

screenshot

int 5

int 6

int 7

### CODE REVIEW

**Comment by julie-sullivan** [comment]
1. Can you fix the errors first
2. What sorts of things do you think I should test? Do you have suggestions for what might "go wrong"?

My list so far:

* can make a list with an organism name
* can make a list without an organism name
* organism name -- doesn't exist, is misspelled etc. Is error handled properly?
* Can create a list of ontology terms. (these don't have an organism relationship)

Thanks!

**Comment by nkengawoh** [comment]
@julie-sullivan 
I have corrected the PEP issues.
I do not have any more suggestions on your list of test cases.

Thanks!

**Comment by julie-sullivan** [comment]
@rachellyne Can you test this to make sure it does what you want?

**Comment by rachellyne** [comment]
@nkengawoh  Can you check this with genes where there is the potential to create the wrong gene due to multiple entries with the same symbol?  You can do this in humanMine with example genes pparg and pax6.  If you query humanMine with either of these genes you will see there is an entry for human, mouse and rat.  If we are uploading a list with this symbol, we probably only want the gene from a specified organism (say human).   I can't tell whether this works from your example as there is only one gene for each in flymine, so it would automatically create the correct gene anyway.

**Comment by nkengawoh** [comment]
@rachellyne Thank you for pointing that out.
Here is the test you requested:
hm1
hm-2

**Comment by nkengawoh** [comment]
@julie-sullivan @rachellyne 
Have you had a look?

**Comment by yochannah** [comment]
@nkengawoh I'm taking a look at this now. Could you try merging the current intermine / dev branch into this PR? There don't seem to be any conflicts and it might fix the travis build failure! :+1:

**Comment by nkengawoh** [comment]
@yochannah 
Thanks for having a close look at this.
I have merged the current dev branch into this PR, and now the travis build passes.
You are right about the Error handling. I did not work on that.
I shall now handle errors concerning this PR in a better way; and shall also write unit tests for this PR.

For the sake of this PR/functionality, I think it is best that, after this, I create another issue for error handling in the repo, to handle such errors more generally.

**Comment by yochannah** [comment]
@nkengawoh let us know when you're ready for this to be re-reviewed! :smile_cat:

**Comment by nkengawoh** [comment]
@yochannah @rachellyne 
Sorry for the silence and delay. I got caught up with a lot of things. 

I have written the tests for this feature, however, I used flymine and not the employee test model; because I am not familiar with it and it does not have Genes, among other things.

However, I cannot fully run the live tests, they fail with the error:
`
    raise ModelError("'" + name + "' is not a class in this model")
intermine.model.ModelError: "'Employee' is not a class in this model"
`

Is there anything I missed?

**Comment by yochannah** [comment]
hmmm, testing for organism doesn't seem easy to translate to the employee model, does it. 

@julie-sullivan - any suggestions?

**Comment by julie-sullivan** [comment]
no, no suggestions.

https://github.com/intermine/intermine-ws-python/tree/dev/tests - the bio tests seem to test on the live webapp.

Or make the code generic enough to be tested in the testmine. I know in the code we have abstracted it away to be `extraValue`, I don't know if that was also done in the testmine.

**Comment by nkengawoh** [comment]
@yochannah @julie-sullivan 

Yes, it does not translate well to the employee model.

I think I will go with Julie's hint, but I shall complete this after I finish up the GSoC proposal, if that is fine by you.

Thanks.

**Comment by yochannah** [comment]
That's a good plan! :)

**Comment by julie-sullivan** [comment]
@yochannah can I merge this? We had another request for this functionality today! :)

**Pull request merged**
