### PR TITLE
Get all intermines

### PR DESCRIPTION
**Pull request by arun-y99**
Addressing issue #46 

Modified function getMines() in registry.py

When no organism is given, it prints out the list of all intermines.

```
>>> from intermine import registry
>>> registry.getMines()
BMAP
BeanMine
BovineMine
CHOmine
ChickpeaMine
CowpeaMine
FlyMine
GrapeMine
HumanMine
HymenopteraMine
IndigoMine
LegumeMine
LocustMine
MaizeMine
MedicMine
MitoMiner
ModMine
MouseMine
OakMine
PeanutMine
PhytoMine
PlanMine
RatMine
RepetDB
SoyMine
TargetMine
ThaleMine
WheatMine
WormMine
XenMine
YeastMine
ZebrafishMine
```

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@arun-y99 so so sorry but I've just updated the travis config: https://github.com/intermine/intermine-ws-python/commit/e3b9eee59321fb14c3ed98063cabe481a60fd4c6

Can you pull that into your branch and try again?

Thank you!! :)

**Comment by arun-y99** [comment]
@julie-sullivan the build is supposed to fail right?

Pandas and Matplotlib are not supported yet by pypy and pypy3
http://packages.pypy.org/##pandas

**Comment by arun-y99** [comment]
@yochannah can you please review?

**Comment by yochannah** [comment]
Hey @arun-y99! Thanks for your contribution and sorry for the delay reviewing 😕  I'm travelling at the moment but will be in the office next week, then we'll definitely get on it. ❤️

**Comment by arun-y99** [comment]
Yeah okay cool!

**Pull request merged**
