### PR TITLE
Patch 1: Adds a dataframe feature for a query

### PR DESCRIPTION
**Pull request by mbasil09**
solves #39

### CODE REVIEW

**Comment by mbasil09** [comment]
closes #39

**Comment by mbasil09** [comment]
@yochannah @julie-sullivan 
Try this. If you find some errors, do tell me, I'll try to fix those.

**Comment by yochannah** [comment]
@mbasil09 Thanks! I'll take a look at the functionality imminently. Do you think it's safe to ignore the long lines here and assume they'll be fixed in your other PR?

**Comment by mbasil09** [comment]
@yochannah 
Please ignore the PEP8 bot here. 
I am solving those queries in #65.

**Pull request merged**
