### PR TITLE
Solved outstanding bugs

### PR DESCRIPTION
**Pull request by nupurgunwant**
Made the following changes:
- changes pandas version to '0.22.0'
- changed the output of get_query() to return xml
- made bar-charts python2.7 compatible

### CODE REVIEW

**Comment by julie-sullivan** [comment]
@nupurgunwant if you fix so this passes, I will merge + test!

**Comment by julie-sullivan** [comment]
Visualisation doesn't work for me in Python 2 or 3. Looks like we might have more missing requirements?

```
julie ~/git/nupur $ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from intermine import bar_chart as b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "intermine/bar_chart.py", line 14, in <module>
    import pandas as pd
ImportError: No module named pandas
>>> quit()

julie ~/git/nupur $ python3
Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from intermine import bar_chart as b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local-data/git/nupur/intermine/bar_chart.py", line 15, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/__init__.py", line 127, in <module>
    from . import cbook
ImportError: cannot import name 'cbook'
```

**Comment by nupurgunwant** [comment]
@julie-sullivan , I tried using newly made environments of specifically these python versions you indicated in the previous comment. I then used the following commands:
``` python setup.py install
pip install -r requirements.txt```
Its working for me.

**Comment by julie-sullivan** [comment]
@nupurgunwant  please fix the tests so I can test!

**Comment by julie-sullivan** [comment]
I ran those two commands:

```
julie ~/git/nupur $ sudo python setup.py install
[sudo] password for julie: 
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/intermine-1.09.09.egg-info
Writing /usr/local/lib/python2.7/dist-packages/intermine-1.09.09.egg-info
julie ~/git/nupur $ pip install -r requirements.txt
Requirement already satisfied: Requests==2.18.4 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 2)) (2.18.4)
Requirement already satisfied: Lxml==4.2.1 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 3)) (4.2.1)
Requirement already satisfied: Unittest2==1.1.0 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: Numpy==1.14.5 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 5)) (1.14.5)
Requirement already satisfied: Pandas==0.22.0 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 6)) (0.22.0)
Requirement already satisfied: matplotlib==2.2.2 in /usr/local/lib/python3.4/dist-packages (from -r requirements.txt (line 7)) (2.2.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.4/dist-packages (from Requests==2.18.4->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.4/dist-packages (from Requests==2.18.4->-r requirements.txt (line 2)) (2018.4.16)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.4/dist-packages (from Requests==2.18.4->-r requirements.txt (line 2)) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.4/dist-packages (from Requests==2.18.4->-r requirements.txt (line 2)) (1.22)
Requirement already satisfied: argparse in /usr/local/lib/python3.4/dist-packages (from Unittest2==1.1.0->-r requirements.txt (line 4)) (1.4.0)
Requirement already satisfied: six>=1.4 in /usr/lib/python3/dist-packages (from Unittest2==1.1.0->-r requirements.txt (line 4)) (1.5.2)
Requirement already satisfied: traceback2 in /usr/local/lib/python3.4/dist-packages (from Unittest2==1.1.0->-r requirements.txt (line 4)) (1.4.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.4/dist-packages (from Pandas==0.22.0->-r requirements.txt (line 6)) (2018.5)
Requirement already satisfied: python-dateutil>=2 in /usr/local/lib/python3.4/dist-packages (from Pandas==0.22.0->-r requirements.txt (line 6)) (2.6.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.4/dist-packages (from matplotlib==2.2.2->-r requirements.txt (line 7)) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.4/dist-packages (from matplotlib==2.2.2->-r requirements.txt (line 7)) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/lib/python3/dist-packages (from matplotlib==2.2.2->-r requirements.txt (line 7)) (2.0.1)
Requirement already satisfied: linecache2 in /usr/local/lib/python3.4/dist-packages (from traceback2->Unittest2==1.1.0->-r requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.4/dist-packages (from kiwisolver>=1.0.1->matplotlib==2.2.2->-r requirements.txt (line 7)) (36.0.1)
```
Then I failed on the first line:

```
julie ~/git/nupur $ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from intermine import bar_chart as b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "intermine/bar_chart.py", line 14, in <module>
    import pandas as pd
ImportError: No module named pandas
```

I understand it works for you, but we need it to work for everyone, even people who do not have pandas or cbook installed.

**Comment by julie-sullivan** [comment]
The first google search says you need a wheel not an egg: https://stackoverflow.com/questions/33481974/importerror-no-module-named-pandas

Try that? `pip list` shows that I have pandas installed.

```
julie ~/git/gradle/testmine $ pip list
Package                       Version           
----------------------------- ------------------
apturl                        0.5.2ubuntu4      
backports-abc                 0.5               
bcdoc                         0.12.0            
bleach                        2.0.0             
botocore                      0.29.0            
Brlapi                        0.6.1             
certifi                       2018.4.16         
chardet                       3.0.4             
checkbox                      0.17.7.dev0       
checkbox-ng                   0.3               
checkbox-support              0.2               
colorama                      0.2.5             
coloredlogs                   9.0               
command-not-found             0.3               
cycler                        0.10.0            
decorator                     4.0.11            
defer                         1.0.6             
dirspec                       13.10             
docutils                      0.11              
entrypoints                   0.2.2             
feedparser                    5.1.3             
friends                       0.1               
html5lib                      0.999999999       
httplib2                      0.8               
humanfriendly                 4.8               
idna                          2.6               
intermine                     1.9.9             
ipykernel                     4.6.1             
ipython                       6.1.0             
ipython-genutils              0.2.0             
ipywidgets                    6.0.0             
jedi                          0.10.2            
Jinja2                        2.9.6             
jmespath                      0.2.1             
jprops                        2.0.2             
jsonschema                    2.6.0             
jupyter                       1.0.0             
jupyter-client                5.0.1             
jupyter-console               5.1.0             
jupyter-core                  4.3.0             
kiwisolver                    1.0.1             
language-selector             0.1               
lightdm-gtk-greeter-settings  1.1.0             
linecache2                    1.0.0             
louis                         2.5.3             
lxml                          4.2.1             
Mako                          0.9.1             
MarkupSafe                    1.0               
matplotlib                    2.2.2             
mistune                       0.7.4             
nbconvert                     5.2.1             
nbformat                      4.3.0             
notebook                      5.0.0             
numpy                         1.14.5            
oauthlib                      0.6.1             
onboard                       1.0.1             
oneconf                       0.3.7.14.4.1      
pandas                        0.22.0            
pandocfilters                 1.4.1             
pexpect                       4.2.1             
pickleshare                   0.7.4             
Pillow                        2.3.0             
pip                           18.0              
piston-mini-client            0.7.5             
plainbox                      0.5.3             
ply                           3.4               
prompt-toolkit                1.0.14            
ptyprocess                    0.5.1             
pycrypto                      2.6.1             
pycurl                        7.19.3            
Pygments                      1.6               
pygobject                     3.12.0            
pyparsing                     2.0.1             
python-apt                    0.9.3.5ubuntu2    
python-dateutil               2.6.0             
python-debian                 0.1.21-nmu2ubuntu2
pytz                          2018.5            
pyxdg                         0.25              
pyzmq                         16.0.2            
qtconsole                     4.3.0             
requests                      2.18.4            
roman                         2.0.0             
rsa                           3.1.2             
screen-resolution-extra       0.0.0             
setuptools                    36.0.1            
simplegeneric                 0.8.1             
simplejson                    3.11.1            
six                           1.5.2             
software-center-aptd-plugins  0.0.0             
terminado                     0.6               
testpath                      0.3.1             
thin-client-config-agent      0.8               
tornado                       4.5.1             
traceback2                    1.4.0             
traitlets                     4.3.2             
typing                        3.6.1             
ubuntu-drivers-common         0.0.0             
ufw                           0.34-rc-0ubuntu2  
unattended-upgrades           0.1               
unittest2                     1.1.0             
unity-scope-audacious         0.1               
unity-scope-calculator        0.1               
unity-scope-chromiumbookmarks 0.1               
unity-scope-clementine        0.1               
unity-scope-colourlovers      0.1               
unity-scope-devhelp           0.1               
unity-scope-firefoxbookmarks  0.1               
unity-scope-gdrive            0.7               
unity-scope-gmusicbrowser     0.1               
unity-scope-gourmet           0.1               
unity-scope-guayadeque        0.1               
unity-scope-manpages          0.1               
unity-scope-musique           0.1               
unity-scope-openclipart       0.1               
unity-scope-texdoc            0.1               
unity-scope-tomboy            0.1               
unity-scope-virtualbox        0.1               
unity-scope-yelp              <============-> 93% EXECUTING [17h 28m 57s]
unity-scope-zotero            0.1               
urllib3                       1.22              
usb-creator                   0.2.23            
virtkey                       0.63.0            
wcwidth                       0.1.7             
webencodings                  0.5.1             
wheel                         0.24.0            
widgetsnbextension            2.0.0             
xdiagnose                     3.6.3build2       
xkit                          0.0.0  
```

**Comment by julie-sullivan** [comment]
```
Steps to test:
==> from intermine import bar_chart as b
==>b.save_mine_and_token("humanmine","T1p6E3FdZ689o8o9c0W7")
==>b.plot_go_vs_p("PL_obesityMonogen_ORahilly09")
"""Plots GO Terms vs p-value"""
==>b.plot_go_vs_count("PL_obesityMonogen_ORahilly09")
"""Plots GO Term vs gene-count"""
==>b.query_to_barchart_log('<query model="genomic" view="Gene.name Gene.symbol Gene.length" sortOrder="Gene.name ASC" ><constraint path="Gene.length" op="&lt;" value="450074" /><constraint path="Gene.name" op="=" value="translation initiation factor IF-2-like" /></query>','true')
"""Plots the query given in xml (second column vs third column)"""
```

**Comment by julie-sullivan** [comment]
Everything worked when I upgraded to Python 3.6.5:
```
julie ~ $ python3 --version
Python 3.6.5 :: Anaconda, Inc.
```
Didn't work on 2.7 but that's okay, we are dropping support for that next year.

Will merge in when the tests pass!

**Pull request merged**
