### PR TITLE
Added docs folder and modified .gitignore

### PR DESCRIPTION
**Pull request by nupurgunwant**
In reference to #4 

- Added a folder named 'docs' containing all html files

### CODE REVIEW

**Comment by yochannah** [comment]
This is really handy! I think there might be a couple of tweaks we could make, though. 

The files have this header:

image


- It has your home directory in the filepath :smile:  not the end of the world, but is there maybe a switch to change that or remove it entirely? 
- is there a way to get an index page? Neither of the following exist:  
   - the top left "intermine" links to intermine.html
   - the top right "index" links to the doc root (i.e. index.html)

**Comment by nupurgunwant** [comment]
As far as I read about pydocs [here](https://docs.python.org/3/library/pydoc.html), I don't think there is a way to make changes in the generated page. 
But if the pages are generated in one's PC, they will be able to open the index ( & the file path )
ie if you run these:
```
$ pydoc -w intermine.constraints
$ open ./intermine.constraints.html
```
you will be able to open the top right links.

**Comment by yochannah** [comment]
Hmmm. I agree, pydoc is a bit old and non-configurable, isn't it?

What about sphinx? `sphinx-apidoc --full -o docs intermine` seems to produce something reasonable (more: http://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html )

**Comment by yochannah** [comment]
This is really nice, @nupurgunwant - thanks for the update to sphinx! 

would it be possible to deploy the built html version to gh-pages for this repo? That would put it live at 

http://www.intermine.org/intermine-ws-python/intermine.html

... I think

**Comment by nupurgunwant** [comment]
Do you want me to add the docs folder in 'gh-pages' branch , instead of 'docs' branch?

You can also host it on github using master branch as stated [here](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)

**Comment by yochannah** [comment]
@julie-sullivan do you have a preference? I don't mind what branch it's on, so long as I end up with a URL I can give to my tutorial people next week :grin:

**Pull request merged**
