### PR TITLE
PEP8 Update

### PR DESCRIPTION
**Pull request by mbasil09**
Changed some obvious files using autopep8 and coala-bears.
There are still some minor PEP8 errors remaining, but they will require manual changes.(eg:- long comments, ambiguous variables)

### CODE REVIEW

**Comment by mbasil09** [comment]
@yochannah 
Many of the PEP8 errors are fixed, except for some very long lines.
Do you want me to manually fix these lines?
Also, we have used some very vague variable names (like 'l' for list), this does not adhere to PEP8 guidelines. Do you want me to change them to some more meaningful variable names?

**Comment by yochannah** [comment]
@mbasil09 yes, both of those would be amazing! Those long lines can be tricky so I would suggest to be careful that tests still pass - perhaps make a few small changes and push each time rather than doing it in a large batch.

**Comment by mbasil09** [comment]
@pep8speaks  pep8ify

**Comment by yochannah** [comment]
@mbasil09 this is truly heroic effort - just dropping byto offer a word of encouragement and thanks :) 💖

**Comment by mbasil09** [comment]
> @mbasil09 this is truly heroic effort - just dropping byto offer a word of encouragement and thanks :) 💖

thank you so much, this means a lot.

PS: I am from India and there have been nation-wide protests, which is why my work has been slow.
I'll try to complete this as fast as possible as soon as I get the time.

**Comment by mbasil09** [comment]
@yochannah 
most of the errors are fixed.

I have intentionally left out a few, since changing them would make the code less readable, which would be counter-intuitive since PEP8 wants to make the code more readable.

test_core.py has some really, really long lines which require a mind better than mine to fix.
I would take a look at them later if I get the chance. For now, this is how much I can contribute.

**Comment by mbasil09** [comment]
keep the issue open for someone who would like to change test_core.py

**Comment by yochannah** [comment]
@mbasil09 wow, you've done _so_ much on this - I really can't thank you enough :) If you send an email to yo@intermine.org and share your physical mailing address, I can pop some InterMine stickers in the post as a thank you! 🚀

**Pull request merged**
