### PR TITLE
handle new error behaviour in python 3.7 - fixes #40

### LINKED ISSUE #40: calling `service.get_template()` triggers an error in Python 3.7
Executing `service.get_template()` in Python 3.7 results in `RuntimeError: generator raised StopIteration`. The example is below is when accessing FlyMine; however, I have seen the same thing happens for YeastMine.
Demonstrating the issue:
Go to [here](https://github.com/intermine/intermine-ws-python-docs) and scroll fown to the 'Tutorial 7: Templates' section. Under there click the `launch binder` badge and try running the first cell after the session spins up. The error will come up. as currently the Binder instances are defaulting to Python 3.7.

Example output from the demonstration:
stopiteration_ error_with_template_example

I suspect it is related to the second item under 'Changes in Python Behavior' [here](https://docs.python.org/3.7/whatsnew/3.7.html#changes-in-python-behavior) as currently the Binder instances are defaulting to Python 3.7.. A possible fix to a related issue is shown [here](https://stackoverflow.com/a/51701040/8508004). It looks like incorporating that approach to line 477 of `intermine/query.py` may fix it.

### PR DESCRIPTION
**Pull request by yochannah**
small fix for #40. This fixes it on my machine when running 3.7.

Travis is failing on environmental setup issues (Java) and I can't figure out why. This is four lines different from the intermine dev branch!

@julie-sullivan could you help by any chance? It would be nice to have this available for the GCC workshop next week.

### CODE REVIEW

**Comment by julie-sullivan** [comment]
Does this include changes in #38?

**Comment by yochannah** [comment]
No - should it?

**Comment by yochannah** [comment]
okay, it appears that the _same commit_ passed on the PR pipeline even though it failed on my personal branch. Let's pretend my branch never failed as it's clearly some sort of environment issue. :sob:

**Comment by julie-sullivan** [comment]
> No - should it?

1. Take a look. Maybe? There are some small changes but then a big one in ListManager that needs testing.

2. Do you need me to test? What should I be looking for?

3. There are instructions on how to publish the python client in the google drive under "python client".

**Comment by yochannah** [comment]
Hmmmm.

> > No - should it?
> 
>     1. Take a look. Maybe? There are some small changes but then a big one in ListManager that needs testing.

The big one in ListManager is really hard to review as it's a mix of whitespace and actual code changes. It would be nice to leave it until later.  
 
>     2. Do you need me to test? What should I be looking for?

This only affects `get_template` -(I hope). You can see the full error in #40. To reproduce, run this: 

```python
from intermine.webservice import Service
service = Service("www.flymine.org/flymine/service")
template = service.get_template('Gene_Pathway')
print("flymine", template.views)
```

If it doesn't error under python 3.7 (and no other errors crop up - I'd suggest running both test suites) then we should be good to go! 

To test different python versions, I did this to create a new environment (assuming you have anaconda installed): 

```bash
conda create -n template_bug35 python=3.5
conda activate template_bug35
conda install -c bioconda intermine
```
replace with 3.7 in the above code to test in python 3.7. You'll need to install intermine (the python package) each time you activate a new environment

>     3. There are instructions on how to publish the python client in the google drive under "python client".

cool - let me know if you think it's ready / once this is merged! :)

**Comment by julie-sullivan** [comment]
```
julie ~/scripts $ python3.7 templates.py 
Traceback (most recent call last):
  File "/local-homes/julie/.local/lib/python3.7/site-packages/intermine/query.py", line 478, in group
    yield tuple([next(itr) for i in range(count)])
  File "/local-homes/julie/.local/lib/python3.7/site-packages/intermine/query.py", line 478, in <listcomp>
    yield tuple([next(itr) for i in range(count)])
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "templates.py", line 5, in <module>
    template = service.get_template('Gene_Pathway')
  File "/local-homes/julie/.local/lib/python3.7/site-packages/intermine/webservice.py", line 447, in get_template
    t = Template.from_xml(t, self.model, self)
  File "/local-homes/julie/.local/lib/python3.7/site-packages/intermine/query.py", line 487, in from_xml
    for path, direction in group(sos, 2):
RuntimeError: generator raised StopIteration

```

This is the file:

```

#!/usr/bin/env python

from intermine.webservice import Service
service = Service("www.flymine.org/flymine/service")
template = service.get_template('Gene_Pathway')
print("flymine", template.views)

```

I am thinking this is my fault? I am happy to merge in if you have tested!

**Comment by julie-sullivan** [comment]
Tested! Works great! Ready to publish.

**Pull request merged**
